### ISSUE TITLE
rack 3.0 support

### ISSUE THREAD

**Issue by metapsj** [soveran/cuba#101]
will cuba support rack 3.0?

here some of the changes that effect cuba.

- Extract rackup command, Rack::Server, Rack::Handler and related code into a separate gem. 
- Moved Rack::Session into separate gem.
- Response header keys can no longer include uppercase characters.
- Rack::Headers added to support lower-case header keys.

i've included links to rack 3.0's changelog and upgrade guide as a connivence. 

change log
https://github.com/rack/rack/blob/3.0.0/CHANGELOG.md

upgrade guide
https://github.com/rack/rack/blob/3.0.0/UPGRADE-GUIDE.md

**Comment by soveran** [comment]
Thanks for raising this issue! I will work on this next week.

**Comment by dariojg** [comment]
Hello @soveran, Do you have any idea when they’ll release this PR? https://github.com/soveran/cuba/pull/102.  I see it's  open since December. I'm interested in this issues because I use cuba that uses rack and I want resolve vulnerabilities in my projects caused by cuba using rack.

**Comment by soveran** [comment]
@dariojg I've just pushed version 4.0.0, can you test it?

Thanks!

**Comment by dariojg** [comment]
@soveran, I appreciate the prompt response!.

Updated Cuba to version 4.0.0 and works well!. And the Rack vulnerabilties are solved.

Thanks and Regards!

**Comment by soveran** [comment]
@dariojg Thank you!
