### ISSUE TITLE
Use of partials

### ISSUE THREAD

**Issue by microspino** [soveran/cuba#54]
I would like to extract a partial with some html from my layout.mote.
I was unable to find a easier solution than this:

__layout.mote__
```
...
{{ this.partial('mypartial') }}
...
```

then inside __views/mypartial.mote__ i have some html content.
```
<p>This is the content of my partial.</p>
```
Is this the right way to do it?

BTW I like this little framework A LOT. 
:clap: **Thx for the nice job** :clap:

**Comment by frodsan** [comment]
This issue can be closed.
