### ISSUE TITLE
Proposal: remove `header` API

### ISSUE THREAD

**Issue by larrylv** [soveran/cuba#61]
`header` [API](https://github.com/soveran/cuba/blob/8e0e77d8a20cdce7ffdf78d4b92d63d2f68c8bb6/lib/cuba.rb#L266) was introduced in bf5f62868fc9a076358b254072af118dc909e28f, but with no examples or instructions on how to use it and also no tests of it.

Actually from the name `header`, we assume it's used to ensure the request has some header with it, but http header in the env hash should be start with `HTTP_` prefix. So the correct implementation might be

``` ruby
  ENV_HTTP_HEADER_PREFIX = "HTTP_".freeze
  def header(key)
    lambda { env["#{ENV_HTTP_HEADER_PREFIX}_#{key}".upcase.tr("-","_")] }
  end
```

Or the user has to call `header('HTTP_KEYNAME')` if he/she wants to make sure the `KEYNAME` exist in the header.

So, as I mentioned early, since there are no examples, instructions and tests on how to use it. Should cuba just remove it?

Or if you are concerned about breaking the backward compatibility, I will be happy to contribute some docs and tests on it.

**Comment by soveran** [comment]
Thanks a lot for your input! It was removed in the [4.0.0 working branch](https://github.com/cuba-rb/cuba/pull/6).

**Comment by larrylv** [comment]
Glad to help. :)

**Comment by moonglum** [comment]
Should this be closed? :smile:
