### ISSUE TITLE
The Guide to Cuba is down?

### ISSUE THREAD

**Issue by axdg** [soveran/cuba#63]
Not sure if this is the right forum for this, but [The Guide to Cuba](http://theguidetocuba.io/) doesn't appear to be available - It looks like the domain has expired. Is this available somewhere else?

**Comment by maynkj** [comment]
Yes, the domain was expired and have now been reactivated. It might take up to 24 hours before everything is back to normal. Thank you for letting us know! :)

**Comment by axdg** [comment]
Yep, it's back up already. Cheers.
