### ISSUE TITLE
where can I change the server port

### ISSUE THREAD

**Issue by lostpupil** [soveran/cuba#70]
Sorry for this question, but I went through the doc and code twice. 
Didn't see anything mention how to change the port.

**Comment by frodsan** [comment]
If you are using `rackup`:

```
$ rackup --port 8282

# or

$ rackup -p 8282
```

If you are using another server, most of them have the same option. With `puma`:

```
$ puma -p 8282
```

**Comment by lostpupil** [comment]
thank you for that, I have figure that out, it turns out port isn't related to cuba.
