### ISSUE TITLE
[Suggestion] Adds support for beerpay.io

### ISSUE THREAD

**Issue by chebyte** [soveran/cuba#78]
Hi @soveran , first congrats for all your projects, I have been used many of them for a lot of projects, cuba, ost, micromachine, etc...
I want to invite to you to add some projects to beerpay.io, so I can support them , and retribute at least some of everything you do for us
about Beerpay, it is a free plataform for support open source project and help them to grow up, I'm inviting to all people, who has projects that I'm using, for support them

thanks for all!

**Comment by soveran** [comment]
Thanks a lot for the kind words :-)

I'll close this because I may not add this soon, but thanks a lot anyway for the contribution and for the offer!
