### ISSUE TITLE
Reference in Readme to Cuba::TextHelpers

### ISSUE THREAD

**Issue by carlosipe** [soveran/cuba#83]
I quote:
`That's the simplest kind of plugin you'll write. In fact, that's exactly how the markdown helper is written in Cuba::TextHelpers.`

Where is Cuba::TextHelpers? Is it some cuba-contrib project I don't know about? Thanks

**Comment by soveran** [comment]
Hey @carlosipe! Yes, it's part of [cuba-contrib](https://github.com/cyx/cuba-contrib). I haven't used that library in years, but I think it should work just fine :-)

**Comment by soveran** [comment]
A similar library is [cuba-sugar](https://github.com/elcuervo/cuba-sugar).

**Comment by carlosipe** [comment]
Thank you, @soveran! Sorry for not googling better before asking, my bad. I am a proud user of Cuba  since a RubyConf in Uruguay (I think it was four years ago) after a quick chat with Cecilia Rivero and you, so I'll take this opportunity to say: thank you! :D

**Comment by soveran** [comment]
@carlosipe On the contrary, thank _you_ for being so supportive!
