### ISSUE TITLE
help need for parameters type check 

### ISSUE THREAD

**Issue by lostpupil** [soveran/cuba#86]
Hello, I have used Cuba for several projects. Here is a question I have came up with:

```ruby
 on param('content'), param('user_id'), param('post_id') do |content, uid, pid|
      # both content, uid, pid will be string
 end
```

So, Is there any solution to build a function to do something like:

```ruby
 on string('content'), int('user_id'), int('post_id') do |content, uid, pid|
      # so that content, uid, pid will be string, int, and int like
 end
```

So I do that convert with to_i, to_s, and other methods. Also I check the doc, turns out matchers won't do that favor.  Is there any suggestions to do parameters check and type cast in Cuba way?

**Comment by soveran** [comment]
Hello @lostpupil, I think there could be a way to do that. I'll check and I'll get back to you.

**Comment by lostpupil** [comment]
@soveran Thank you so much. I have been searching around for two days, still got no idea.

**Comment by soveran** [comment]
Here's an idea for a plugin:

```ruby
module TypedParams
  def int(key)
    value = req[key]
    lambda { captures << value.to_i unless value.to_s.empty? }
  end
end
```

Then you can use it like this:

```ruby
Cuba.plugin TypedParams

Cuba.define do
  on int("user_id") do |user_id|
    # Here, user_id is a number
  end
end
```

What do you think?

**Comment by lostpupil** [comment]
@soveran brilliant！
