### ISSUE TITLE
Serving static files using Rack::Static not working

### ISSUE THREAD

**Issue by whiskeykontequila** [soveran/cuba#87]
I'm trying to serve static files from Cuba using Rack::Static @ ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]:

`
Cuba.use Rack::Static, :urls => %w("/css" "/js"), :root => "public"
`

But I keep on getting 404s. I tried all combinations - removing :root, moving /css from public/ to /, using :urls => { "/css/style.css" => ... using string keys instead of symbols in Rack::Static configuration ... - but nothing seams to work.

Thanks !

**Comment by whiskeykontequila** [comment]
I just tried to downgrade to 3.7.0 and it works ! :) So the problem is only in new version (3.8.0)

**Comment by soveran** [comment]
@whiskeykontequila It looks like it works for me even with 3.8.0, did you run into any other issues?

**Comment by soveran** [comment]
As it is working for me, I will close the issue. Please let me know how it went for you and we will reopen this if necessary to continue with the investigation.
