### ISSUE TITLE
add json support

### ISSUE THREAD

**Issue by lostpupil** [soveran/cuba#89]
Normally, I can call routes by

```
curl -XPOST localhost:3000/api -d "a=123"
```

And I notice most client request library call a api default using json payload.

So, Is there any plan to add that to the cuba?

**Comment by F-3r** [comment]
Hello! Cuba user here.

I think there's not need to add anything to Cuba to support json.
First you'll need to send the correct request (the curl request you are creating is not sending json but application/x-www-form-urlencoded).

Then just setting the correct content type header in the response should be enough.

See https://github.com/soveran/ox/blob/master/routes/users.rb for an example

**Comment by lostpupil** [comment]
@F-3r Thanks for your responding, and I know exactly how to make a json response. 
If you call the api with application/x-www-form-urlencoded. Yes, you can get the response as  you excepted. but json is very flexible and it won't be checked by `on` statement if you know what I mean.

```
on param('hello') do |hello|
end
```

Actually, I think I need a param check util,  something like grape's params check to help me do some validation. No matter it's application/x-www-form-urlencoded or application/json.

Cuba currently support form data and urlencoded, they will be processed by `on` statement, but the json payload won't get there. So if I want to get the json payload. I need to do something like this below:

```
JSON.parse env['rack.input'].read
```

**Comment by soveran** [comment]
Maybe you can get inspiration from the `read/write` methods in Satz:

https://github.com/syro/satz/blob/master/lib/satz.rb#L82-L91

[Satz](https://github.com/syro/satz) is a tool for building JSON APIs with [Syro](http://soveran.github.io/syro/). Syro and Cuba are very similar, so you can easily transfer ideas from one to the other.

**Comment by lostpupil** [comment]
@soveran Thank you man. :) That would be very nice.
