### ISSUE TITLE
undefined method `DelegateClass' for Rack::Session::Cookie:Class (NoMethodError)

### ISSUE THREAD

**Issue by tablecell** [soveran/cuba#98]
/Ruby27/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/session/cookie.rb:155:in `<class:Cookie>': undefined method `DelegateClass' for Rack::Session::Cookie:Class (NoMethodError)
hele_world.rb
```C
require "cuba"
require "cuba/safe"

Cuba.use Rack::Session::Cookie, :secret => "__a_very_long_string__"

Cuba.plugin Cuba::Safe

Cuba.define do
  on get do
    on "hello" do
      res.write "Hello world!"
    end

    on root do
      res.redirect "/hello"
    end
  end
end
```

**Comment by soveran** [comment]
@tablecell Thanks for reporting this issue. It looks like it's a known bug in Rack: https://github.com/rack/rack/pull/1610

I added a workaround and pushed the version 3.9.3.

**Comment by tablecell** [comment]
bty   
```C
on "username/:username" do |username|
      user = User.find_by_username(username) # username == "foobar"
```
 is User extends from ApplicationRecord ?    is there any crud example code for database  ,such as  blog  post /list

**Comment by soveran** [comment]
I think it should work just fine with ActiveRecord or any other ORM. Can you give it a try and tell me how it goes?
